"""產出 STELLOGLOSSA_Report.md,包含統計摘要與最有趣個案。"""
from __future__ import annotations

import json
import logging
from collections import Counter
from pathlib import Path
from typing import Any

import networkx as nx
import numpy as np

from config import DATA_PROCESSED, OUTPUT_DIR, PHONOLOGY_DIR

log = logging.getLogger(__name__)


def _load_all():
    pulsars = json.loads((DATA_PROCESSED / "pulsars.json").read_text(encoding="utf-8"))
    profiles = [json.loads(p.read_text(encoding="utf-8")) for p in sorted(PHONOLOGY_DIR.glob("*.json"))]
    from config import LEXICON_DIR
    lexicons = [json.loads(p.read_text(encoding="utf-8")) for p in sorted(LEXICON_DIR.glob("*.json"))]
    graph = nx.read_graphml(OUTPUT_DIR / "contact_graph.graphml")
    hypo = json.loads((OUTPUT_DIR / "hypothesis_results.json").read_text(encoding="utf-8"))
    return pulsars, profiles, lexicons, graph, hypo


def _distribution(profiles: list[dict[str, Any]]) -> dict[str, Any]:
    syllables = Counter(p["syllable_structure"] for p in profiles)
    tones = Counter(p["tone_count"] for p in profiles)
    tense = Counter(p["tense_richness"] for p in profiles)
    vowel_sizes = Counter(len(p["vowel_inventory"]) for p in profiles)
    return {
        "syllable_structures": dict(syllables),
        "tone_counts": dict(sorted(tones.items())),
        "tense_richness": dict(tense),
        "vowel_inventory_sizes": dict(sorted(vowel_sizes.items())),
    }


def _top_k(items, key, k=3, reverse=True):
    return sorted(items, key=key, reverse=reverse)[:k]


def build_markdown() -> str:
    pulsars, profiles, lexicons, graph, hypo = _load_all()
    dist = _distribution(profiles)

    most_complex = _top_k(profiles, lambda p: p["complexity_score"], k=3)
    simplest = _top_k(profiles, lambda p: p["complexity_score"], k=3, reverse=False)

    degrees = [(n, graph.degree(n)) for n in graph.nodes]
    hubs = sorted(degrees, key=lambda x: x[1], reverse=True)[:3]
    isolates = [n for n, d in degrees if d == 0]

    lines = [
        "# STELLOGLOSSA Research Report",
        "",
        f"*Generated from {hypo['summary']['n_pulsars']} pulsars, "
        f"{hypo['summary']['n_lexicons']} lexicons, "
        f"{hypo['summary']['graph_edges']} contact edges.*",
        "",
        "## 1. 音系類型分布",
        "",
        "| 維度 | 分布 |",
        "|------|------|",
        f"| 音節結構 | {dist['syllable_structures']} |",
        f"| 聲調數量 | {dist['tone_counts']} |",
        f"| 時態豐富度 | {dist['tense_richness']} |",
        f"| 母音系統大小 | {dist['vowel_inventory_sizes']} |",
        "",
        "## 2. 假說驗證結果",
        "",
        "| 假說 | 通過 | 統計量 | p-value | 效應量 | 說明 |",
        "|------|:----:|-------:|--------:|-------:|------|",
    ]
    for r in hypo["results"]:
        status = "✅" if r["passed"] else "❌"
        effect = f"{r['effect_size']:.3f}" if r["effect_size"] is not None else "—"
        lines.append(
            f"| {r['name']} | {status} | {r['statistic']:.3f} | {r['p_value']:.4f} | "
            f"{effect} | {r['notes']} |"
        )

    lines += [
        "",
        "## 3. 最複雜的語言 (complexity_score)",
        "",
        "| 脈衝星 | 星座 | 音節 | 聲調 | 母音 | 分數 |",
        "|--------|------|------|:----:|:----:|-----:|",
    ]
    for p in most_complex:
        lines.append(
            f"| {p['jname']} | {p['constellation']} | {p['syllable_structure']} | "
            f"{p['tone_count']} | {len(p['vowel_inventory'])} | {p['complexity_score']} |"
        )

    lines += [
        "",
        "## 4. 最簡單的語言",
        "",
        "| 脈衝星 | 星座 | 音節 | 聲調 | 母音 | 分數 |",
        "|--------|------|------|:----:|:----:|-----:|",
    ]
    for p in simplest:
        lines.append(
            f"| {p['jname']} | {p['constellation']} | {p['syllable_structure']} | "
            f"{p['tone_count']} | {len(p['vowel_inventory'])} | {p['complexity_score']} |"
        )

    lines += [
        "",
        "## 5. 接觸網絡中心 (degree hubs)",
        "",
        "| 脈衝星 | 度數 |",
        "|--------|-----:|",
    ]
    for n, d in hubs:
        lines.append(f"| {n} | {d} |")
    if isolates:
        lines.append("")
        lines.append(f"**孤島** ({len(isolates)} 顆): {', '.join(isolates[:10])}")

    lines += ["", "---", "*Report auto-generated by `src/analysis/report_writer.py`.*", ""]
    return "\n".join(lines)


def run() -> Path:
    md = build_markdown()
    path = OUTPUT_DIR / "STELLOGLOSSA_Report.md"
    path.write_text(md, encoding="utf-8")
    log.info("wrote %s", path)
    return path


if __name__ == "__main__":
    logging.basicConfig(level=logging.INFO)
    run()
